// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLh_qBD1FO8DHqr2aJalSexKje4Vsvus',
    appId: '1:1022191114899:web:11b9bfb139ac05806f8b66',
    messagingSenderId: '1022191114899',
    projectId: 'sui-project-205d4',
    authDomain: 'sui-project-205d4.firebaseapp.com',
    storageBucket: 'sui-project-205d4.firebasestorage.app',
    measurementId: 'G-5JC87C52PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Kb-mDFX1vDhSpTLeciFHzcgvdlJPKa0',
    appId: '1:1022191114899:android:3180c5e5643cb6fe6f8b66',
    messagingSenderId: '1022191114899',
    projectId: 'sui-project-205d4',
    storageBucket: 'sui-project-205d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlMEtFMZADFe9km7tzbnFOG7djSZzZJIU',
    appId: '1:1022191114899:ios:ac4c3b249cae0e2d6f8b66',
    messagingSenderId: '1022191114899',
    projectId: 'sui-project-205d4',
    storageBucket: 'sui-project-205d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlMEtFMZADFe9km7tzbnFOG7djSZzZJIU',
    appId: '1:1022191114899:ios:ac4c3b249cae0e2d6f8b66',
    messagingSenderId: '1022191114899',
    projectId: 'sui-project-205d4',
    storageBucket: 'sui-project-205d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjLh_qBD1FO8DHqr2aJalSexKje4Vsvus',
    appId: '1:1022191114899:web:6cc569f262a3dfdf6f8b66',
    messagingSenderId: '1022191114899',
    projectId: 'sui-project-205d4',
    authDomain: 'sui-project-205d4.firebaseapp.com',
    storageBucket: 'sui-project-205d4.firebasestorage.app',
    measurementId: 'G-W2XL5M93NK',
  );
}
